# Generated by Django 3.0.8 on 2020-08-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200809_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booksImg/', verbose_name='Постер'),
        ),
    ]
