# Generated by Django 3.0.8 on 2020-08-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200810_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='booksImg/', width_field='width_field'),
        ),
    ]
